name: Cypress Tests frontend

on: [workflow_dispatch, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    name: E2E in Chrome on ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@6c143abc292aa835d827652c2ea025d098311070
        with:
          working-directory: frontend
          install-command: yarn --frozen-lockfile --silent --network-timeout 1000000
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          spec: cypress/e2e/**/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_API_URL: http://localhost:3001/api
          DOMAIN_NAME: localhost
          PORT: 3000
          BASE_PATH: ""
          HEALTH_AUTH: false
          HEALTH_USERNAME: ""
          HEALTH_PASSWORD: ""
